
openconf:
  build: .
  ports:
    - 80:80
  links:
    - mariadb
  restart: always
  volumes:
    - ./oc_data:/var/www/html/data

mariadb:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw
  restart: always
  volumes:
    - ./db_data:/var/lib/mysql
