services:
  openconf:
    build: .
    ports:
      - 1881:80
    links:
      - mariadb
    restart: always
    volumes:
      - ./data/oc_data:/var/www/html/data
      - ./config.php:/var/www/html/config.php:ro

  mariadb:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: openconf
      MYSQL_PASSWORD: openconf
      MYSQL_DATABASE: openconf
    restart: always
    volumes:
      - ./data/db_data:/var/lib/mysql
